-- Identify gaps below XX threshold between bicycle infra or between bicycle infra and intersections
-- mark as bicycle infra assumed
-- make sure to mark that is is assumed - to test for importance/difference!