# Settings for connecting to database and filepaths for input data

CRS: 'EPSG:25832'

db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
db_password: 'aneitu'

# filepaths for input data
osm_fp: "/Users/anev/Library/CloudStorage/Dropbox/ITU/repositories/dk_bicycle_network/data/raw/road_networks/denmark-latest.osm.pbf" #'../data/raw/road_networks/denmark-latest.osm.pbf'

geodk_fp: '../data/raw/road_networks/vejmidte_hist.gpkg'
geodk_hist: True

muni_fp: '../data/raw/study_area/muni_boundary.gpkg'

urban_fp1: "../data/raw/urban/zonekort_samlet_v.gpkg"
urban_fp2: "../data/raw/urban/bebyggelse.gpkg"


osm_style_file: "/Users/anev/Library/CloudStorage/Dropbox/ITU/repositories/dk_bicycle_network/resources/modified.style"
lua_style_file: "/Users/anev/Library/CloudStorage/Dropbox/ITU/repositories/dk_bicycle_network/resources/style.lua"
