name: dk_bike_network
channels:
  - conda-forge
  - conda
  - defaults
dependencies:
  - affine=2.4.0
  - appnope=0.1.3
  - asttokens=2.4.1
  - attrs=23.1.0
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.10
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.0
  - aws-c-http=0.8.0
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.10.0
  - aws-c-s3=0.4.7
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blosc=1.21.5
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.21.0
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - ceres-solver=2.1.0
  - certifi=2023.11.17
  - cfitsio=4.3.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.1.4
  - contourpy=1.2.0
  - coverage=7.3.2
  - curl=8.5.0
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - draco=1.5.6
  - eigen=3.4.0
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - exiv2=0.27.6
  - expat=2.5.0
  - fiona=1.9.5
  - folium=0.15.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.44.0
  - freetype=2.12.1
  - freexl=2.0.0
  - future=0.18.3
  - gdal=3.7.2
  - geoalchemy2=0.14.2
  - geopandas=0.14.0
  - geopandas-base=0.14.0
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.78.1
  - glib-tools=2.78.1
  - glog=0.6.0
  - gmp=6.2.1
  - greenlet=3.0.1
  - gsl=2.7
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - h3-py=3.7.6
  - hdf4=4.2.15
  - hdf5=1.14.2
  - httplib2=0.22.0
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - json-c=0.17
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kealib=1.5.2
  - khronos-opencl-icd-loader=2023.04.17
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - laz-perf=3.4.0
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-flight=14.0.2
  - libarrow-flight-sql=14.0.2
  - libarrow-gandiva=14.0.2
  - libarrow-substrait=14.0.2
  - libblas=3.9.0
  - libboost-headers=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.7.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libogg=1.3.4
  - libopenblas=0.3.24
  - libopus=1.3.1
  - libparquet=14.0.2
  - libpng=1.6.39
  - libpq=15.4
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libxslt=1.1.37
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.4
  - lxml=4.9.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.3
  - matplotlib-base=3.8.1
  - matplotlib-inline=0.1.6
  - metis=5.1.0
  - minizip=4.0.2
  - mock=5.1.0
  - mpfr=4.2.1
  - munch=4.0.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - networkx=3.2.1
  - nitro=2.7.dev8
  - nose2=0.9.2
  - nspr=4.35
  - nss=3.94
  - numpy=1.26.0
  - openjpeg=2.5.0
  - openssl=3.2.0
  - orc=1.9.2
  - owslib=0.29.3
  - packaging=23.2
  - pandas=2.1.2
  - parso=0.8.3
  - pcre2=10.40
  - pdal=2.5.6
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=3.11.0
  - plotly=5.18.0
  - ply=3.11
  - poppler=23.08.0
  - poppler-data=0.4.12
  - postgresql=15.4
  - proj=9.3.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - psycopg2=2.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pygments=2.16.1
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebkit=5.15.9
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qca=2.3.7
  - qgis=3.34.0
  - qjson=0.9.0
  - qscintilla2=2.14.1
  - qt-main=5.15.8
  - qtkeychain=0.14.1
  - qtwebkit=5.212
  - qwt=6.2.0
  - rasterio=1.3.9
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - rioxarray=0.15.0
  - rtree=1.1.0
  - scikit-learn=1.3.2
  - scipy=1.11.3
  - setuptools=68.2.2
  - shapely=2.0.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlalchemy=2.0.23
  - sqlite=3.44.0
  - stack_data=0.6.2
  - suitesparse=5.10.1
  - tbb=2021.10.0
  - tenacity=8.2.3
  - threadpoolctl=3.2.0
  - tiledb=2.16.3
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.13.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzcode=2023c
  - tzdata=2023c
  - uriparser=0.9.7
  - urllib3=2.0.7
  - wcwidth=0.2.9
  - wheel=0.41.3
  - xarray=2023.10.1
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
