name: dk_bike_network
channels:
  - conda-forge
  - conda
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - azure-core-cpp=1.11.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blosc=1.21.5
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.25.0
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - certifi=2023.11.17
  - cfitsio=4.3.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fiona=1.9.5
  - folium=0.15.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.2
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.8.3
  - geoalchemy2=0.14.3
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - greenlet=3.0.3
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json-c=0.17
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-flight=14.0.2
  - libarrow-flight-sql=14.0.2
  - libarrow-gandiva=14.0.2
  - libarrow-substrait=14.0.2
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.8.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libparquet=14.0.2
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.4
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.3
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - minizip=4.0.4
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.9
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.96
  - numpy=1.26.3
  - openjpeg=2.5.0
  - openssl=3.2.0
  - orc=1.9.2
  - packaging=23.2
  - pandas=2.1.4
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.2
  - pixman=0.43.0
  - platformdirs=4.1.0
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.1
  - proj=9.3.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.7
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.1
  - python-dateutil=2.8.2
  - python-tzdata=2023.4
  - python_abi=3.12
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - rtree=1.1.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - setuptools=69.0.3
  - shapely=2.0.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlalchemy=2.0.25
  - sqlite=3.44.2
  - stack_data=0.6.2
  - threadpoolctl=3.2.0
  - tiledb=2.19.0
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzcode=2023d
  - tzdata=2023d
  - uriparser=0.9.7
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
